name: Team A Deploy

on:
  push:
    branches: [main]

jobs:
  deploy:
    # --- ADD THESE THREE LINES ---
    permissions:
      id-token: write
      contents: read
    # -----------------------------
    uses: shivtestac/demo-proj/.github/workflows/deploy.yml@main
    with:
      team: Team-a
      app_name: app1
